version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam2:debian-stable
        environment:
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Install system deps
          command: |
            sudo apt install m4 -y -qq
      - restore_cache:
          key: cache-{{ checksum "junit.opam" }}-{{ checksum "junit_alcotest.opam" }}-{{ checksum "junit_ounit.opam" }}
      - run:
          name: Update opam package list
          command: opam update
      - run:
          name: 'Install deps'
          command: opam install . --deps-only
      - save_cache:
          key: cache-{{ checksum "junit.opam" }}-{{ checksum "junit_alcotest.opam" }}-{{ checksum "junit_ounit.opam" }}
          paths:
            - ~/.opam
      - run:
          name: Build
          command: opam pin add -y .
      - run:
          name: Test
          command: eval `opam config env` && make test
      - run:
          name: Collect xml reports
          command: |
            mkdir -p ~/reports
            cp _build/default/junit/test/simple.xml ~/reports
            cp _build/default/alcotest/test/alcotest_report.xml ~/reports
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
