version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam:ubuntu-17.04_ocaml-4.02.3
        environment:
          TERM: xterm
    steps:
      - checkout
      - run:
          name: build
          command: |
            opam pin add -y junit .
            opam pin add -y junit_ounit .
            opam pin add -y junit_alcotest .
      - run:
          name: test
          command: eval `opam config env` && make test
      - run:
          name: collect xml reports
          command: |
            mkdir -p ~/reports
            cp _build/default/junit/test/simple.xml ~/reports
            cp _build/default/alcotest/test/alcotest_report.xml ~/reports
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
